name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          mkdir output
          cd output
          ../scripts/build.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: podman rootfs for WSL2
          path: output/podman.tar.xz
